name: Ping Render n8n

on:
  schedule:
    # 1️⃣ Primeira rotina: começa às 7h BR (10h UTC) e roda a cada 5 minutos
    - cron: "*/5 10-21 * * 1-5"

    # 2️⃣ Segunda rotina: começa 3 minutos depois (7h03 BR / 10h03 UTC)
    - cron: "3-59/5 10-21 * * 1-5"

    # 3️⃣ Terceira rotina: começa 3 minutos depois da anterior (7h06 BR / 10h06 UTC)
    - cron: "6-59/5 10-21 * * 1-5"

    # 3️⃣ Quarta rotina: começa 3 minutos depois da anterior (7h09 BR / 10h09 UTC)
    - cron: "9-59/5 10-21 * * 1-5"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n server
        run: |
          echo "Ping para manter o n8n acordado"
          curl -s https://n8n-project-3h24.onrender.com > /dev/null
