name: Railway Scheduler

on:
  workflow_dispatch: # permite rodar manualmente se precisar
  schedule:
    # roda a cada hora entre 08h e 20h de segunda a sexta
    - cron: "0 8-20 * * 1-5"

jobs:
  railway:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@v2.0.0
        with:
          timezone: "America/Sao_Paulo"

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Login Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Garantir que app está rodando entre 08h e 20h
        run: |
          HORA=$(date +%H)
          if [ $HORA -ge 8 ] && [ $HORA -lt 9 ]; then
            echo "🔵 Horário comercial -> Ligando app"
            railway up
          else
            echo "⚪ Fora do horário -> Desligando app"
            railway down
          fi
