name: Railway Scheduler

on:
  schedule:
    - cron: '0 10 * * 1-5' # Liga Postgres + n8n às 07h BR
    - cron: '15 16 * * 1-5' # Desliga n8n + Postgres às 20:00 BR
  workflow_dispatch:

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Start Postgres (07h BR)
        run: |
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.POSTGRES_SERVICE_ID }} --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Start n8n (07h BR)
        run: |
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.N8N_SERVICE_ID }} --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Stop n8n (20:00 BR)
        run: |
          railway down --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.N8N_SERVICE_ID }} --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Stop Postgres (20:00 BR)
        run: |
          railway down --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.POSTGRES_SERVICE_ID }} --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
