name: Railway Scheduler

on:
  schedule:
    - cron: '0 11 * * 1-5' # Liga 08h BR
    - cron: '0 23 * * 1-5' # Desliga 20h BR
  workflow_dispatch:

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Start Service (08h BR)
        if: github.event.schedule == '0 11 * * 1-5'
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Authorization: Bearer $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { serviceInstanceStart(id: \"'"$SERVICE_ID"'\") { id status } }"}'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Stop Service (20h BR)
        if: github.event.schedule == '0 23 * * 1-5'
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Authorization: Bearer $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { serviceInstanceStop(id: \"'"$SERVICE_ID"'\") { id status } }"}'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
