name: Railway Deploy Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação (deploy ou stop)"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - stop

jobs:
  railway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Railway CLI
        run: npm install -g railway

      - name: Executar ação no Railway
        run: |
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            railway up --service 56c4dc9a-fb1d-4348-b54d-c6c288446457 --environment ce1b5218-62f7-4004-8a1e-fc1818d55ec9 --project d4315485-5b4c-4445-8759-70a589bd6ee6
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            railway down --service 56c4dc9a-fb1d-4348-b54d-c6c288446457 --environment ce1b5218-62f7-4004-8a1e-fc1818d55ec9 --project d4315485-5b4c-4445-8759-70a589bd6ee6
          else
            echo "Ação inválida"
            exit 1
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
