name: Railway Down

on:
  schedule:
    # Executa de segunda a sexta-feira às 23:00 (UTC), que corresponde às 20:00 BRT.
    - cron: '0 23 * * 1-5'
  workflow_dispatch:

jobs:
  down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop Project
        run: railway down -- --service ${{secrets.N8N_SERVICE}}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
