name: Railway Down

on:
  schedule:
    - cron: '0 23 * * 1-5'   # 20h BR
  workflow_dispatch:

jobs:
  down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop Project
        run: railway down
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
