name: Railway Down

on:
  schedule:
    # Executa de segunda a sexta-feira às 23:00 (UTC), que corresponde às 20:00 BRT.
    - cron: '0 23 * * 1-5'
  workflow_dispatch:

jobs:
  down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login no Railway
        run: railway login -b
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Conection
        run: railway ssh --project=d4315485-5b4c-4445-8759-70a589bd6ee6 --environment=ce1b5218-62f7-4004-8a1e-fc1818d55ec9 --service=56c4dc9a-fb1d-4348-b54d-c6c288446457
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Stop Project
        run: railway down -s ${{secrets.N8N_SERVICE}}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
